# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-23 13:54
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='name')),
                ('cpf', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('cod_area', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('ASPIRANTE', 'ASPIRANTE'), ('REGULAR', 'REGULAR'), ('EFETIVO', 'EFETIVO'), ('ADMINISTRADOR', 'ADMINISTRADOR')], max_length=20, verbose_name='categoria')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo')),
                ('is_active', models.BooleanField(default=False)),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
