# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-23 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('ASPIRANTE', 'ASPIRANTE'), ('REGULAR', 'REGULAR'), ('EFETIVO', 'EFETIVO')], max_length=100),
        ),
    ]
