# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170323_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.URLField(default='http://placehold.it/50x50'),
        ),
    ]
