# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170324_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.URLField(default='http://placehold.it/50x50'),
        ),
    ]
