# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170324_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to=b''),
        ),
    ]
