# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 21:45
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170324_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
    ]
